# Node.js with React
# Build a Node.js project that uses React.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- main

pool:
  name: Default

steps:

- task: NodeTool@0
  inputs:
    versionSource: 'spec'
    versionSpec: '20.x'
  displayName: 'Install Node.js'


- script: |
    echo Running Vite build
    cd FRONTEND
    npm install
    npm run build
  workingDirectory: FRONTEND
  displayName: 'Build React App'

- script: |
    echo ===== WHERE AM I =====
    cd
    echo ===== ROOT CONTENT =====
    dir
    echo ===== FRONTEND CONTENT =====
    dir FRONTEND
    echo ===== FRONTEND SUBFOLDERS =====
    dir FRONTEND\*
  displayName: "DEBUG: Show folders"
  
- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: 'FRONTEND/dist'
    ArtifactName: 'frontend-dist'
    publishLocation: Container
  displayName: "Publish Frontend Artifcats"
