# Node.js with React
# Build a Node.js project that uses React.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- main

pool:
  name: Default

steps:
- script: |
    echo Running Vite build
    cd FRONTEND
    npm install
    npm run build
  workingDirectory: FRONTEND
  displayName: 'Build React App'

- script: |
    echo ===== WHERE AM I =====
    cd
    echo ===== ROOT CONTENT =====
    dir
    echo ===== FRONTEND CONTENT =====
    dir FRONTEND
    echo ===== FRONTEND SUBFOLDERS =====
    dir FRONTEND\*
  displayName: "DEBUG: Show folders"
  
- script: |
    echo Copying build output to server folder
    xcopy "$(Build.SourcesDirectory)\FRONTEND\dist" "C:\u01\buildsrv\AzureDevopAutomation_Practice" /E /I /Y

    echo Deployment successfully
  displayName: "Deploy in winScp server folder"
